# Generated by Django 2.0 on 2018-02-02 11:48

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecocases', '0002_ecocasecomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='ecocase',
            name='description',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AddField(
            model_name='ecocase',
            name='promise',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AddField(
            model_name='ecocase',
            name='label',
            field=models.ManyToManyField(to='ecocases.Label'),
        ),
    ]
