# Generated by Django 2.0 on 2018-02-02 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecocases', '0004_auto_20180202_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecocase',
            name='image',
        ),
        migrations.AddField(
            model_name='ecocaseimage',
            name='ecocase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecocases.Ecocase'),
        ),
    ]
