# Generated by Django 2.0 on 2018-02-03 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecocases', '0005_auto_20180202_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='Ecocase2ESM',
            new_name='Association',
        ),
        migrations.AddField(
            model_name='evaluation',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecocases.Association'),
        ),
    ]
