# Generated by Django 2.0 on 2018-02-03 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecocases', '0006_auto_20180203_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='answer',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='question',
            field=models.ManyToManyField(to='ecocases.Question'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
