# Generated by Django 2.0 on 2018-02-04 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecocases', '0007_auto_20180203_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='esm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecocases.ESM'),
        ),
    ]
