# Generated by Django 2.0 on 2018-02-05 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecocases', '0010_auto_20180205_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecocase',
            old_name='category',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='ecocase',
            old_name='level',
            new_name='levels',
        ),
    ]
