# Generated by Django 2.0 on 2018-02-17 23:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecocases', '0012_auto_20180206_0909'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Association',
            new_name='Ecocase2ESM',
        ),
        migrations.RenameModel(
            old_name='Evaluation',
            new_name='ESMEvaluation',
        ),
        migrations.RenameField(
            model_name='esmevaluation',
            old_name='association',
            new_name='ecocase2esm',
        ),
    ]
