# Generated by Django 2.0 on 2018-02-26 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecocases', '0013_auto_20180217_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='esmevaluation',
            name='is_first_esm',
            field=models.NullBooleanField(default=False),
        ),
    ]
