# Generated by Django 2.0 on 2018-02-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecocases', '0015_esmevaluation_is_second_esm'),
    ]

    operations = [
        migrations.AddField(
            model_name='esm',
            name='logo_url',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='esm',
            name='pdf_url',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
