# Generated by Django 2.0 on 2018-02-28 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecocases', '0017_esm_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecocase',
            name='associated_esms',
        ),
    ]
