# Generated by Django 2.0 on 2018-02-28 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecocases', '0019_ecocase_associated_esms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecocase',
            name='associated_esms',
        ),
        migrations.AddField(
            model_name='ecocase',
            name='first_esm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_esm', to='ecocases.ESM'),
        ),
        migrations.AddField(
            model_name='ecocase',
            name='second_esm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_esm', to='ecocases.ESM'),
        ),
    ]
